pub mod app;
pub mod fonts;
pub mod formatting;
pub mod highlight;
pub mod icon;
pub mod model;
pub mod search;
pub mod serial_worker;
pub mod settings;
pub mod store;
mod terminal;
pub mod theme;
pub mod window_chrome;
